include(GoogleTest)

function(add_gmock_test target)
    set(target ${target}_tests)
    add_executable(${target} ${test_srcs})
    add_dependencies(${target} googletest)
    target_link_libraries(${target} ${test_libs} ${GMOCK_BOTH_LIBRARIES} ${Boost_LIBRARIES} ${JSONCPP_LIBRARIES} pthread)
    target_include_directories(${target} PRIVATE ${JSONCPP_INCLUDE_DIRS})
    gtest_discover_tests(${target})
    unset(test_srcs)
    unset(test_libs)
endfunction()
