import {filter, includes} from "lodash";
import fs from 'fs';
import {PATH_TO_DAEMON} from './features/00-setup';

module.exports = {
    logFileExists: () => {
        // Log file is generated by Daemon in /daemon folder
        return filter(logDirContent('/daemon'), file => includes(file, '.log'))[0];
    },
    logFileMoved: logFileName => {
        // Log file is moved to /daemon/logs after Daemon is stopped
        return filter(logDirContent('/daemon/logs'), files => includes(files, logFileName))[0];
    },
    readFile: (dirPath, logFileName) => {
        return fs.readFileSync(PATH_TO_DAEMON + dirPath + logFileName, 'utf8');
    }
};

const logDirContent = path =>
    fs.readdirSync(PATH_TO_DAEMON + path);
